import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ParametroService } from '../../Service/parametro.service'
import { Parametro } from 'src/app/Modelo/Parametro';

@Component({
  selector: 'app-parmlist',
  templateUrl: './parmlist.component.html',
  styleUrls: ['./parmlist.component.css']
})
export class ParmlistComponent implements OnInit {
  parametros: Parametro[];
  constructor(private service: ParametroService, private router: Router) {}

 ngOnInit()  {
    this.service.getParametros()
    .subscribe(data => {
      this.parametros = data;
    });
  }

  Editarparametro(parametro:Parametro):void{
    localStorage.setItem("codent",parametro.codent.toString());
    localStorage.setItem("centalta",parametro.centalta.toString());
    localStorage.setItem("producto",parametro.producto.toString());
    localStorage.setItem("subprodu",parametro.subprodu.toString());
    localStorage.setItem("condpro",parametro.condpro.toString());
    localStorage.setItem("codcam",parametro.codcam.toString());
    localStorage.setItem("codconven",parametro.codconven.toString());
    localStorage.setItem("codpromo",parametro.codpromo.toString());
    localStorage.setItem("numper",parametro.numper.toString());
    localStorage.setItem("numperaval",parametro.numperaval.toString());
    localStorage.setItem("indctaemp",parametro.indctaemp.toString());
    localStorage.setItem("indnomemp",parametro.indnomemp.toString());
    localStorage.setItem("nombreemp",parametro.nombreemp.toString());
    localStorage.setItem("codregimen",parametro.codregimen.toString());
    localStorage.setItem("forpago",parametro.forpago.toString());
    localStorage.setItem("indsitcta",parametro.indsitcta.toString());
    localStorage.setItem("grupoliq",parametro.grupoliq.toString());
    localStorage.setItem("grupocuo",parametro.grupocuo.toString());
    localStorage.setItem("ofiven",parametro.ofiven.toString());
    localStorage.setItem("clamon1",parametro.clamon1.toString());
    localStorage.setItem("limcrecta1",parametro.limcrecta1.toString());
    localStorage.setItem("impfpagoa1",parametro.impfpagoa1.toString());
    localStorage.setItem("limcrecom1",parametro.limcrecom1.toString());
    localStorage.setItem("limcrecomg1",parametro.limcrecomg1.toString());
    localStorage.setItem("clamon2",parametro.clamon2.toString());
    localStorage.setItem("limcrecta2",parametro.limcrecta2.toString());
    localStorage.setItem("impfpagoa2",parametro.impfpagoa2.toString());
    localStorage.setItem("limcrecom2",parametro.limcrecom2.toString());
    localStorage.setItem("limcrecomg2",parametro.limcrecomg2.toString());
    localStorage.setItem("ctacargo1",parametro.ctacargo1.toString());
    localStorage.setItem("clamoncon1",parametro.clamoncon1.toString());
    localStorage.setItem("inddomcarcre",parametro.inddomcarcre.toString());
    localStorage.setItem("codformato",parametro.codformato.toString());
    localStorage.setItem("ctadomtar1",parametro.ctadomtar1.toString());
    localStorage.setItem("monctatar1",parametro.monctatar1.toString());
    localStorage.setItem("indactpas1",parametro.indactpas1.toString());
    localStorage.setItem("ctadomtar2",parametro.ctadomtar2.toString());
    localStorage.setItem("monctatar2",parametro.monctatar2.toString());
    localStorage.setItem("indactpas2",parametro.indactpas2.toString());
    localStorage.setItem("numpertar",parametro.numpertar.toString());
    localStorage.setItem("calparttar",parametro.calparttar.toString());
    localStorage.setItem("indtipttar",parametro.indtipttar.toString());
    localStorage.setItem("codmartar",parametro.codmartar.toString());
    localStorage.setItem("nombenredtar",parametro.nombenredtar.toString());
    localStorage.setItem("idempleadotar",parametro.idempleadotar.toString());
    localStorage.setItem("panasoctar",parametro.panasoctar.toString());
    localStorage.setItem("codbarrastar",parametro.codbarrastar.toString());
    localStorage.setItem("reffototar",parametro.reffototar.toString());
    localStorage.setItem("estplastar1",parametro.estplastar1.toString());
    localStorage.setItem("estplastar2",parametro.estplastar2.toString());
    localStorage.setItem("idenvesttar",parametro.idenvesttar.toString());
    localStorage.setItem("centesttar",parametro.centesttar.toString());
    localStorage.setItem("indenvpintar",parametro.indenvpintar.toString());
    localStorage.setItem("centpintar",parametro.centpintar.toString());
    localStorage.setItem("condesttar",parametro.condesttar.toString());
    localStorage.setItem("codpromotar",parametro.codpromotar.toString());
    localStorage.setItem("clamon1tar",parametro.clamon1tar.toString());
    localStorage.setItem("limdiacaj1tar",parametro.limdiacaj1tar.toString());
    localStorage.setItem("maxdiacaj1tar",parametro.maxdiacaj1tar.toString());
    localStorage.setItem("clamon2tar",parametro.clamon2tar.toString());
    localStorage.setItem("limdiacaj2tar",parametro.limdiacaj2tar.toString());
    localStorage.setItem("maxdiacaj2tar",parametro.maxdiacaj2tar.toString());
    localStorage.setItem("cuenta",parametro.cuenta.toString());
    localStorage.setItem("desclamon",parametro.desclamon.toString());
    localStorage.setItem("fecalta",parametro.fecalta.toString());
    localStorage.setItem("pantar",parametro.pantar.toString());
    localStorage.setItem("fecaltatar",parametro.fecaltatar.toString());
    localStorage.setItem("feccadtar",parametro.feccadtar.toString());
    localStorage.setItem("desmarredtar",parametro.desmarredtar.toString());
    localStorage.setItem("destiptredtar",parametro.destiptredtar.toString());
    localStorage.setItem("indsittartar",parametro.indsittartar.toString());
    localStorage.setItem("dessittartar",parametro.dessittartar.toString());
    localStorage.setItem("feccobcuo",parametro.feccobcuo.toString());
    localStorage.setItem("desclamon1",parametro.desclamon1.toString());
    localStorage.setItem("desclamon2",parametro.desclamon2.toString());
    localStorage.setItem("contcur",parametro.contcur.toString());
    localStorage.setItem("nsecficcab",parametro.nsecficcab.toString());
    localStorage.setItem("tipocintacab",parametro.tipocintacab.toString());
    localStorage.setItem("numregtotcab",parametro.numregtotcab.toString());
    localStorage.setItem("edocintacab",parametro.edocintacab.toString());
    localStorage.setItem("validacioncab",parametro.validacioncab.toString());
    localStorage.setItem("nsecficdet",parametro.nsecficdet.toString());
    localStorage.setItem("tipocintadet",parametro.tipocintadet.toString());
    localStorage.setItem("indcampoinfodet",parametro.indcampoinfodet.toString());
    localStorage.setItem("tipobonc1",parametro.tipobonc1.toString());
    localStorage.setItem("resemiext",parametro.resemiext.toString());
    localStorage.setItem("indpercuo",parametro.indpercuo.toString());
    localStorage.setItem("nummestot",parametro.nummestot.toString());
    localStorage.setItem("numfacsc",parametro.numfacsc.toString());
    localStorage.setItem("seqplastico",parametro.seqplastico.toString());
    localStorage.setItem("tipobont1",parametro.tipobont1.toString());
    localStorage.setItem("indactlim",parametro.indactlim.toString());
    localStorage.setItem("indcamlim",parametro.indcamlim.toString());
    localStorage.setItem("visaphone",parametro.visaphone.toString());
    localStorage.setItem("indfoto",parametro.indfoto.toString());
    localStorage.setItem("maxoper",parametro.maxoper.toString());
    localStorage.setItem("maxodia",parametro.maxodia.toString());
    localStorage.setItem("indcta",parametro.indcta.toString());
    localStorage.setItem("indajena",parametro.indajena.toString());
    localStorage.setItem("indtipcta",parametro.indtipcta.toString());
    localStorage.setItem("cccproduc",parametro.cccproduc.toString());
    localStorage.setItem("cccsubpro",parametro.cccsubpro.toString());
    localStorage.setItem("nsecficfin",parametro.nsecficfin.toString());
    localStorage.setItem("tipocintafin",parametro.tipocintafin.toString());
    localStorage.setItem("edocintafin",parametro.edocintafin.toString());
    localStorage.setItem("validacionfin",parametro.validacionfin.toString());
    localStorage.setItem("limcretar",parametro.limcretar.toString());
    localStorage.setItem("limcremes",parametro.limcremes.toString());
    localStorage.setItem("limdebmes",parametro.limdebmes.toString());
    localStorage.setItem("limcredia",parametro.limcredia.toString());
    localStorage.setItem("limdebdia",parametro.limdebdia.toString());
    
    this.router.navigate(["editparm"]);
  }

  Borrarparametro(parametro:Parametro){
    localStorage.setItem("codent",parametro.codent.toString());
    localStorage.setItem("centalta",parametro.centalta.toString());
    localStorage.setItem("producto",parametro.producto.toString());
    localStorage.setItem("subprodu",parametro.subprodu.toString());
    localStorage.setItem("condpro",parametro.condpro.toString());
    localStorage.setItem("codcam",parametro.codcam.toString());
    localStorage.setItem("codconven",parametro.codconven.toString());
    localStorage.setItem("codpromo",parametro.codpromo.toString());
    localStorage.setItem("numper",parametro.numper.toString());
    localStorage.setItem("numperaval",parametro.numperaval.toString());
    localStorage.setItem("indctaemp",parametro.indctaemp.toString());
    localStorage.setItem("indnomemp",parametro.indnomemp.toString());
    localStorage.setItem("nombreemp",parametro.nombreemp.toString());
    localStorage.setItem("codregimen",parametro.codregimen.toString());
    localStorage.setItem("forpago",parametro.forpago.toString());
    localStorage.setItem("indsitcta",parametro.indsitcta.toString());
    localStorage.setItem("grupoliq",parametro.grupoliq.toString());
    localStorage.setItem("grupocuo",parametro.grupocuo.toString());
    localStorage.setItem("ofiven",parametro.ofiven.toString());
    localStorage.setItem("clamon1",parametro.clamon1.toString());
    localStorage.setItem("limcrecta1",parametro.limcrecta1.toString());
    localStorage.setItem("impfpagoa1",parametro.impfpagoa1.toString());
    localStorage.setItem("limcrecom1",parametro.limcrecom1.toString());
    localStorage.setItem("limcrecomg1",parametro.limcrecomg1.toString());
    localStorage.setItem("clamon2",parametro.clamon2.toString());
    localStorage.setItem("limcrecta2",parametro.limcrecta2.toString());
    localStorage.setItem("impfpagoa2",parametro.impfpagoa2.toString());
    localStorage.setItem("limcrecom2",parametro.limcrecom2.toString());
    localStorage.setItem("limcrecomg2",parametro.limcrecomg2.toString());
    localStorage.setItem("ctacargo1",parametro.ctacargo1.toString());
    localStorage.setItem("clamoncon1",parametro.clamoncon1.toString());
    localStorage.setItem("inddomcarcre",parametro.inddomcarcre.toString());
    localStorage.setItem("codformato",parametro.codformato.toString());
    localStorage.setItem("ctadomtar1",parametro.ctadomtar1.toString());
    localStorage.setItem("monctatar1",parametro.monctatar1.toString());
    localStorage.setItem("indactpas1",parametro.indactpas1.toString());
    localStorage.setItem("ctadomtar2",parametro.ctadomtar2.toString());
    localStorage.setItem("monctatar2",parametro.monctatar2.toString());
    localStorage.setItem("indactpas2",parametro.indactpas2.toString());
    localStorage.setItem("numpertar",parametro.numpertar.toString());
    localStorage.setItem("calparttar",parametro.calparttar.toString());
    localStorage.setItem("indtipttar",parametro.indtipttar.toString());
    localStorage.setItem("codmartar",parametro.codmartar.toString());
    localStorage.setItem("nombenredtar",parametro.nombenredtar.toString());
    localStorage.setItem("idempleadotar",parametro.idempleadotar.toString());
    localStorage.setItem("panasoctar",parametro.panasoctar.toString());
    localStorage.setItem("codbarrastar",parametro.codbarrastar.toString());
    localStorage.setItem("reffototar",parametro.reffototar.toString());
    localStorage.setItem("estplastar1",parametro.estplastar1.toString());
    localStorage.setItem("estplastar2",parametro.estplastar2.toString());
    localStorage.setItem("idenvesttar",parametro.idenvesttar.toString());
    localStorage.setItem("centesttar",parametro.centesttar.toString());
    localStorage.setItem("indenvpintar",parametro.indenvpintar.toString());
    localStorage.setItem("centpintar",parametro.centpintar.toString());
    localStorage.setItem("condesttar",parametro.condesttar.toString());
    localStorage.setItem("codpromotar",parametro.codpromotar.toString());
    localStorage.setItem("clamon1tar",parametro.clamon1tar.toString());
    localStorage.setItem("limdiacaj1tar",parametro.limdiacaj1tar.toString());
    localStorage.setItem("maxdiacaj1tar",parametro.maxdiacaj1tar.toString());
    localStorage.setItem("clamon2tar",parametro.clamon2tar.toString());
    localStorage.setItem("limdiacaj2tar",parametro.limdiacaj2tar.toString());
    localStorage.setItem("maxdiacaj2tar",parametro.maxdiacaj2tar.toString());
    localStorage.setItem("cuenta",parametro.cuenta.toString());
    localStorage.setItem("desclamon",parametro.desclamon.toString());
    localStorage.setItem("fecalta",parametro.fecalta.toString());
    localStorage.setItem("pantar",parametro.pantar.toString());
    localStorage.setItem("fecaltatar",parametro.fecaltatar.toString());
    localStorage.setItem("feccadtar",parametro.feccadtar.toString());
    localStorage.setItem("desmarredtar",parametro.desmarredtar.toString());
    localStorage.setItem("destiptredtar",parametro.destiptredtar.toString());
    localStorage.setItem("indsittartar",parametro.indsittartar.toString());
    localStorage.setItem("dessittartar",parametro.dessittartar.toString());
    localStorage.setItem("feccobcuo",parametro.feccobcuo.toString());
    localStorage.setItem("desclamon1",parametro.desclamon1.toString());
    localStorage.setItem("desclamon2",parametro.desclamon2.toString());
    localStorage.setItem("contcur",parametro.contcur.toString());
    localStorage.setItem("nsecficcab",parametro.nsecficcab.toString());
    localStorage.setItem("tipocintacab",parametro.tipocintacab.toString());
    localStorage.setItem("numregtotcab",parametro.numregtotcab.toString());
    localStorage.setItem("edocintacab",parametro.edocintacab.toString());
    localStorage.setItem("validacioncab",parametro.validacioncab.toString());
    localStorage.setItem("nsecficdet",parametro.nsecficdet.toString());
    localStorage.setItem("tipocintadet",parametro.tipocintadet.toString());
    localStorage.setItem("indcampoinfodet",parametro.indcampoinfodet.toString());
    localStorage.setItem("tipobonc1",parametro.tipobonc1.toString());
    localStorage.setItem("resemiext",parametro.resemiext.toString());
    localStorage.setItem("indpercuo",parametro.indpercuo.toString());
    localStorage.setItem("nummestot",parametro.nummestot.toString());
    localStorage.setItem("numfacsc",parametro.numfacsc.toString());
    localStorage.setItem("seqplastico",parametro.seqplastico.toString());
    localStorage.setItem("tipobont1",parametro.tipobont1.toString());
    localStorage.setItem("indactlim",parametro.indactlim.toString());
    localStorage.setItem("indcamlim",parametro.indcamlim.toString());
    localStorage.setItem("visaphone",parametro.visaphone.toString());
    localStorage.setItem("indfoto",parametro.indfoto.toString());
    localStorage.setItem("maxoper",parametro.maxoper.toString());
    localStorage.setItem("maxodia",parametro.maxodia.toString());
    localStorage.setItem("indcta",parametro.indcta.toString());
    localStorage.setItem("indajena",parametro.indajena.toString());
    localStorage.setItem("indtipcta",parametro.indtipcta.toString());
    localStorage.setItem("cccproduc",parametro.cccproduc.toString());
    localStorage.setItem("cccsubpro",parametro.cccsubpro.toString());
    localStorage.setItem("nsecficfin",parametro.nsecficfin.toString());
    localStorage.setItem("tipocintafin",parametro.tipocintafin.toString());
    localStorage.setItem("edocintafin",parametro.edocintafin.toString());
    localStorage.setItem("validacionfin",parametro.validacionfin.toString());
    localStorage.setItem("limcretar",parametro.limcretar.toString());
    localStorage.setItem("limcremes",parametro.limcremes.toString());
    localStorage.setItem("limdebmes",parametro.limdebmes.toString());
    localStorage.setItem("limcredia",parametro.limcredia.toString());
    localStorage.setItem("limdebdia",parametro.limdebdia.toString());
    this.service.deleteParametro(parametro.codent.toString(),parametro.centalta.toString(),parametro.producto.toString(),parametro.subprodu.toString(),parametro.condpro.toString())
    .subscribe(data=>{
      this.parametros=this.parametros.filter(p=>p!==parametro);
      alert("Parametro eliminado.");
    })
  }

}
